# Student Alcohol Consumption

In [96]:
# importando bibliotecas basicas
import pandas as pd
import numpy as np
import plotly
import plotly.plotly as ply
import plotly.graph_objs as go

plotly.tools.set_credentials_file(username='EulleSilva', api_key='udHtcUnAQHA1wNwQ1f1Q')

## Importando datasets

In [0]:
# Upload do dataset da turma de matemática
from google.colab import files
uploaded = files.upload()
for fn in uploaded.keys():
  print('User uploaded file "{name}" with length {length} bytes'.format(
      name=fn, length=len(uploaded[fn])))

ModuleNotFoundError: No module named 'google'

In [0]:
# Upload do dataset da turma de portugues
from google.colab import files
uploaded = files.upload()
for fn in uploaded.keys():
  print('User uploaded file "{name}" with length {length} bytes'.format(
      name=fn, length=len(uploaded[fn])))

ModuleNotFoundError: No module named 'google'

In [97]:
# Importando dataset da turma de matemática
math_students = pd.read_csv("datasets/student-mat.csv",)

In [98]:
# Importando dataset da turma de matemática
port_students = pd.read_csv("datasets/student-por.csv",)

## Deletar colunas que não serão utilizadas

In [99]:
# Deletar colunas do dataset dos estudantes de Matématica
math_students.drop(math_students.loc[:,['Mjob','Fjob','school','reason','traveltime','paid','nursery']],axis=1,inplace=True)
math_students.columns
# Deletar colunas do datasets/taset dos estudantes de Português
port_students.drop(port_students.loc[:,['Mjob','Fjob','school','reason','traveltime','paid','nursery']],axis=1,inplace=True)
port_students.columns

Index(['sex', 'age', 'address', 'famsize', 'Pstatus', 'Medu', 'Fedu',
       'guardian', 'studytime', 'failures', 'schoolsup', 'famsup',
       'activities', 'higher', 'internet', 'romantic', 'famrel', 'freetime',
       'goout', 'Dalc', 'Walc', 'health', 'absences', 'G1', 'G2', 'G3'],
      dtype='object')

## Adicionar coluna 'student_id'

In [100]:
# Alunos de Matemática
math_students['student_id'] = pd.Series(list(range(0,395)))
cols = math_students.columns.tolist()
a , b = cols.index('sex'), cols.index('student_id')
cols[b] , cols[a] = cols[a] , cols[b]
math_students = math_students[cols]
#math_students

#math_students.to_csv('math_students.csv', sep='\t', encoding='utf-8')

# Alunos de Português
port_students['student_id'] = pd.Series(list(range(0,649)))
cols2 = port_students.columns.tolist()
a , b = cols2.index('sex'), cols2.index('student_id')
cols2[b] , cols2[a] = cols2[a] , cols2[b]
port_students = port_students[cols]
port_students
#port_students.to_csv('port_students.csv', sep='\t', encoding='utf-8')

,student_id,age,address,famsize,Pstatus,Medu,Fedu,guardian,studytime,failures,...,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3,sex
0,0,18,U,GT3,A,4,4,mother,2,0,...,3,4,1,1,3,4,0,11,11,F
1,1,17,U,GT3,T,1,1,father,2,0,...,3,3,1,1,3,2,9,11,11,F
2,2,15,U,LE3,T,1,1,mother,2,0,...,3,2,2,3,3,6,12,13,12,F
3,3,15,U,GT3,T,4,2,mother,3,0,...,2,2,1,1,5,0,14,14,14,F
4,4,16,U,GT3,T,3,3,father,2,0,...,3,2,1,2,5,0,11,13,13,F
5,5,16,U,LE3,T,4,3,mother,2,0,...,4,2,1,2,5,6,12,12,13,M
6,6,16,U,LE3,T,2,2,mother,2,0,...,4,4,1,1,3,0,13,12,13,M
7,7,17,U,GT3,A,4,4,mother,2,0,...,1,4,1,1,1,2,10,13,13,F
8,8,15,U,LE3,A,3,2,mother,2,0,...,2,2,1,1,1,0,15,16,17,M
9,9,15,U,GT3,T,3,4,mother,2,0,...,5,1,1,1,5,0,12,12,13,M
10,10,15,U,GT3,T,4,4,mother,2,0,...,3,3,1,2,2,2,14,14,14,F
11,11,15,U,GT3,T,2,1,father,3,0,...,2,2,1,1,4,0,10,12,13,F
12,12,15,U,LE3,T,4,4,father,1,0,...,3,3,1,3,5,0,12,13,12,M
13,13,15,U,GT3,T,4,3,mother,2,0,...,4,3,1,2,3,0,12,12,13,M
14,14,15,U,GT3,A,2,2,other,3,0,...,5,2,1,1,3,0,14,14,15,M
15,15,16,U,GT3,T,4,4,mother,1,0,...,4,4,1,2,2,6,17,17,17,F
16,16,16,U,GT3,T,4,4,mother,3,0,...,2,3,1,2,2,10,13,13,14,F
17,17,16,U,GT3,T,3,3,mother,2,0,...,3,2,1,1,4,2,13,14,14,F
18,18,17,U,GT3,T,3,2,mother,1,3,...,5,5,2,4,5,2,8,8,7,M
19,19,16,U,LE3,T,4,3,father,1,0,...,1,3,1,3,5,6,12,12,12,M
20,20,15,U,GT3,T,4,3,mother,2,0,...,4,1,1,1,1,0,12,13,14,M
21,21,15,U,GT3,T,4,4,father,1,0,...,4,2,1,1,5,0,11,12,12,M
22,22,16,U,LE3,T,4,2,mother,2,0,...,5,1,1,3,5,0,12,13,14,M
23,23,16,U,LE3,T,2,2,mother,2,0,...,4,4,2,4,5,2,10,10,10,M
24,24,15,R,GT3,T,2,4,mother,3,0,...,3,2,1,1,5,2,10,11,10,F
25,25,16,U,GT3,T,2,2,mother,1,0,...,2,2,1,3,5,6,10,11,12,F
26,26,15,U,GT3,T,2,2,mother,1,0,...,2,2,1,2,5,8,11,12,12,M
27,27,15,U,GT3,T,4,2,mother,1,0,...,2,4,2,4,1,0,11,11,11,M
28,28,16,U,LE3,A,3,4,mother,2,0,...,3,3,1,1,5,2,12,12,13,M
29,29,16,U,GT3,T,4,4,mother,2,0,...,4,5,5,5,5,4,12,11,12,M
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
619,619,18,U,GT3,T,3,3,mother,2,0,...,3,2,1,3,3,6,13,12,13,F
620,620,17,U,LE3,T,4,4,mother,2,0,...,3,4,1,1,1,4,15,14,15,F
621,621,17,R,GT3,T,1,2,father,2,0,...,2,2,1,2,3,0,13,13,13,F
622,622,18,R,GT3,T,1,3,mother,2,0,...,3,4,2,4,3,0,8,10,9,M
623,623,18,U,LE3,T,4,4,mother,3,0,...,2,2,2,2,5,0,15,16,16,M
624,624,17,R,GT3,T,1,1,mother,1,1,...,2,1,1,2,1,0,8,8,9,F
625,625,18,U,GT3,T,2,3,father,1,0,...,2,3,1,2,4,0,10,10,10,F
626,626,18,R,GT3,T,4,4,father,2,0,...,2,2,4,2,5,0,7,5,0,F
627,627,18,R,LE3,T,1,2,father,1,0,...,3,3,2,3,3,3,9,10,10,M
628,628,17,U,GT3,T,2,2,mother,3,0,...,4,3,1,1,3,8,10,11,12,F
629,629,17,R,GT3,T,1,2,mother,1,0,...,5,5,1,3,1,4,7,8,9,F
630,630,18,R,LE3,T,4,4,mother,3,0,...,4,4,1,1,1,0,15,17,17,F
631,631,18,R,GT3,T,1,1,mother,3,0,...,3,2,1,2,4,4,10,11,12,F
632,632,19,R,GT3,T,1,1,other,2,1,...,3,3,1,1,3,4,7,8,9,F
633,633,18,R,LE3,T,4,4,mother,2,0,...,4,3,3,4,2,1,13,14,14,F
634,634,18,U,GT3,T,3,3,mother,2,0,...,1,3,1,2,1,1,16,16,16,F
635,635,17,R,GT3,T,3,1,mother,2,0,...,5,4,2,3,1,10,8,9,9,F
636,636,18,U,GT3,T,4,4,father,2,0,...,2,4,1,4,2,4,17,18,19,M
637,637,18,R,GT3,T,2,1,mother,1,0,...,4,3,1,3,5,0,7,7,0,M
638,638,17,U,GT3,T,2,3,father,2,0,...,4,3,1,1,3,4,14,15,16,M
639,639,19,R,GT3,T,1,1,mother,1,1,...,3,2,1,3,5,0,5,8,0,M
640,640,18,R,GT3,T,4,2,father,1,1,...,4,3,4,3,3,0,7,7,0,M
641,641,18,R,GT3,T,2,2,mother,3,0,...,3,3,1,3,4,0,14,17,15,F
642,642,17,U,GT3,T,4,3,mother,2,0,...,5,4,1,1,1,0,6,9,11,F
643,643,18,R,GT3,T,4,4,mother,1,0,...,4,3,2,2,5,4,7,9,10,F
644,644,19,R,GT3,T,2,3,mother,3,1,...,4,2,1,2,5,4,10,11,10,F
645,645,18,U,LE3,T,3,1,mother,2,0,...,3,4,1,1,1,4,15,15,16,F
646,646,18,U,GT3,T,1,1,mother,2,0,...,1,1,1,1,5,6,11,12,9,F
647,647,17,U,LE3,T,3,1,mother,1,0,...,4,5,3,4,2,6,10,10,10,M
648,648,18,R,LE3,T,3,2,mother,1,0,...,4,1,3,4,5,4,10,11,11,M

## Analisando as caracteristicas dos datasets

In [0]:
# Verificando variaveis da turma de matemática
math_students.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 395 entries, 0 to 394
Data columns (total 33 columns):
school        395 non-null object
sex           395 non-null object
age           395 non-null int64
address       395 non-null object
famsize       395 non-null object
Pstatus       395 non-null object
Medu          395 non-null int64
Fedu          395 non-null int64
Mjob          395 non-null object
Fjob          395 non-null object
reason        395 non-null object
guardian      395 non-null object
traveltime    395 non-null int64
studytime     395 non-null int64
failures      395 non-null int64
schoolsup     395 non-null object
famsup        395 non-null object
paid          395 non-null object
activities    395 non-null object
nursery       395 non-null object
higher        395 non-null object
internet      395 non-null object
romantic      395 non-null object
famrel        395 non-null int64
freetime      395 non-null int64
goout         395 non-null int64
Dalc          395 non-null int64
Walc          395 non-null int64
health        395 non-null int64
absences      395 non-null int64
G1            395 non-null int64
G2            395 non-null int64
G3            395 non-null int64
dtypes: int64(16), object(17)
memory usage: 101.9+ KB

In [0]:
port_students.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 649 entries, 0 to 648
Data columns (total 33 columns):
school        649 non-null object
sex           649 non-null object
age           649 non-null int64
address       649 non-null object
famsize       649 non-null object
Pstatus       649 non-null object
Medu          649 non-null int64
Fedu          649 non-null int64
Mjob          649 non-null object
Fjob          649 non-null object
reason        649 non-null object
guardian      649 non-null object
traveltime    649 non-null int64
studytime     649 non-null int64
failures      649 non-null int64
schoolsup     649 non-null object
famsup        649 non-null object
paid          649 non-null object
activities    649 non-null object
nursery       649 non-null object
higher        649 non-null object
internet      649 non-null object
romantic      649 non-null object
famrel        649 non-null int64
freetime      649 non-null int64
goout         649 non-null int64
Dalc          649 non-null int64
Walc          649 non-null int64
health        649 non-null int64
absences      649 non-null int64
G1            649 non-null int64
G2            649 non-null int64
G3            649 non-null int64
dtypes: int64(16), object(17)
memory usage: 167.4+ KB

In [0]:
math_students.head(5)

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,6,5,6,6
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,4,5,5,6
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,10,7,8,10
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,2,15,14,15
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,4,6,10,10

In [0]:
port_students.head(5)

In [12]:
math_students.shape

(395, 26)

In [13]:
port_students.shape

(649, 26)

## Estudantes de Matemática

In [90]:
# Verificar a distribuição de homens e mulheres
masc = len(math_students[math_students['sex'] == 'M'])
fem = len(math_students[math_students['sex'] == 'F'])
labels = ['Masculino','Feminino']
values = [masc,fem]
colors = ['#96D38C','#E1396C']
trace = go.Pie(labels=labels,values=values,
              hoverinfo='label+percent',textinfo='value',
              textfont=dict(size=20),
              marker=dict(colors=colors,
                         line=dict(color='#000000',width=2)))
ply.iplot([trace],filename='Estudantes de Matématica')

In [91]:
# Distribuição da idade da turma de Matemática

masc_students = math_students[math_students['sex'] == 'M']
fem_students = math_students[math_students['sex'] == 'F']


masc_age = go.Bar(
    x=list(range(masc_students['age'].min(),masc_students['age'].max()+1)),
    y=list(masc_students['age'].value_counts().sort_index()),
    name='Masculino',
    marker=dict(
        color='rgb(49,130,189)'
    )   
)

fem_age = go.Bar(
    x=list(range(fem_students['age'].min(),fem_students['age'].max()+1)),
    y=list(fem_students['age'].value_counts().sort_index()),
    name='Feminino',
    marker=dict(
        color='rgb(204,204,204)',
    )   
)

data = [masc_age, fem_age]
layout = go.Layout(
    xaxis=dict(tickangle=-45),
    barmode='group',
)

fig = go.Figure(data=data, layout=layout)
ply.iplot(fig, filename='angled-text-bar')

## Estudantes de Portugues

In [95]:
# Verificar a distribuição de homens e mulheres
masc = len(port_students[port_students['sex'] == 'M'])
fem = len(port_students[port_students['sex'] == 'F'])
labels = ['Masculino','Feminino']
values = [masc,fem]
colors = ['#96D38C','#E1396C']
trace = go.Pie(labels=labels,values=values,
              hoverinfo='label+percent',textinfo='value',
              textfont=dict(size=20),
              marker=dict(colors=colors,
                         line=dict(color='#000000',width=2)))
ply.iplot([trace],filename='TATAT')

High five! You successfully sent some data to your account on plotly. View your plot in your browser at https://plot.ly/~EulleSilva/0 or inside your plot.ly account where it is named 'TATAT'

In [94]:
#Distribuição de idade da turma de Português
masc_students = port_students[port_students['sex'] == 'M']
fem_students = port_students[port_students['sex'] == 'F']

masc_age = go.Bar(
    x=list(range(masc_students['age'].min(),masc_students['age'].max()+1)),
    y=list(masc_students['age'].value_counts().sort_index()),
    name='Masculino',
    marker=dict(
        color='rgb(49,130,189)'
    )   
)

fem_age = go.Bar(
    x=list(range(fem_students['age'].min(),fem_students['age'].max()+1)),
    y=list(fem_students['age'].value_counts().sort_index()),
    name='Feminino',
    marker=dict(
        color='rgb(204,204,204)',
    )   
)

data = [masc_age, fem_age]
layout = go.Layout(
    xaxis=dict(tickangle=-45),
    barmode='group',
)

fig = go.Figure(data=data, layout=layout)
ply.iplot(fig, filename='angled-text-bar')

# Estudantes de Matemática e Português

In [176]:
# Análisar o consumo de bebida álcoolica por idade dos meninos e das meninas nos dias de trabalho 
stud_math_port = pd.merge(port_students,math_students,how='outer')
df_age_teen = stud_math_port[(stud_math_port['age'] == 15) | (stud_math_port['age'] == 16) | (stud_math_port['age'] == 17)]
df_age_teen['Dalc'].value_counts().sort_index()

df_age_young = stud_math_port[(stud_math_port['age'] == 18) | (stud_math_port['age'] == 19) | (stud_math_port['age'] == 20) | (stud_math_port['age'] == 21) | (stud_math_port['age'] == 22)]
df_age_young['Dalc'].value_counts().sort_index()

trace1 = {
  "x": list(df_age_teen['Dalc'].value_counts().sort_index()), 
  "y": ["Very Low", "Low", "Moderate", "High", "Very High"], 
  "name": "Age: 15-17", 
  "orientation": "h", 
  "type": "bar"
}
trace2 = {
  "x": list(df_age_young['Dalc'].value_counts().sort_index()), 
  "y": ["Very Low", "Low", "Moderate", "High", "Very High"], 
  "name": "Age: 18-22", 
  "orientation": "h", 
  "type": "bar"
}

data = go.Data([trace1, trace2])
layout = {
  "barmode": "group", 
  "title": "Student Consumption Workday alcohol "
}
fig = go.Figure(data=data, layout=layout)
ply.iplot(fig, filename='angled-text-bar')

#df[(df['C']==1) | (df['B']==True)]
#stud_math_port.groupby('Dalc').count()

/home/eulle/.local/lib/python3.6/site-packages/plotly/graph_objs/_deprecations.py:39: DeprecationWarning:

plotly.graph_objs.Data is deprecated.
Please replace it with a list or tuple of instances of the following types
  - plotly.graph_objs.Scatter
  - plotly.graph_objs.Bar
  - plotly.graph_objs.Area
  - plotly.graph_objs.Histogram
  - etc.

In [175]:
# Análisar o consumo de bebida álcoolica por idade dos meninos e das meninas nos finais de semana 

df_age_teen = stud_math_port[(stud_math_port['age'] == 15) | (stud_math_port['age'] == 16) | (stud_math_port['age'] == 17)]
df_age_teen['Walc'].value_counts().sort_index()

df_age_young = stud_math_port[(stud_math_port['age'] == 18) | (stud_math_port['age'] == 19) | (stud_math_port['age'] == 20) | (stud_math_port['age'] == 21) | (stud_math_port['age'] == 22)]
df_age_young['Walc'].value_counts().sort_index()

trace1 = {
  "x": list(df_age_teen['Walc'].value_counts().sort_index()), 
  "y": ["Very Low", "Low", "Moderate", "High", "Very High"], 
  "name": "Age: 15-17", 
  "orientation": "h", 
  "type": "bar"
}
trace2 = {
  "x": list(df_age_young['Walc'].value_counts().sort_index()), 
  "y": ["Very Low", "Low", "Moderate", "High", "Very High"], 
  "name": "Age: 18-22", 
  "orientation": "h", 
  "type": "bar"
}

data = go.Data([trace1, trace2])
layout = {
  "barmode": "group", 
  "title": "Student Consumption Workday alcohol "
}
fig = go.Figure(data=data, layout=layout)
ply.iplot(fig, filename='angled-text-bar')

/home/eulle/.local/lib/python3.6/site-packages/plotly/graph_objs/_deprecations.py:39: DeprecationWarning:

plotly.graph_objs.Data is deprecated.
Please replace it with a list or tuple of instances of the following types
  - plotly.graph_objs.Scatter
  - plotly.graph_objs.Bar
  - plotly.graph_objs.Area
  - plotly.graph_objs.Histogram
  - etc.